In [3]:
def find_first_longest(arr):
    count_zero = 0
    item_com_maior_valor = None
    
    for i in arr:
        tamanho_exato_item = len(str(i))
        if tamanho_exato_item > count_zero:
            count_zero = tamanho_exato_item
            item_com_maior_valor = i
    return item_com_maior_valor

#[1, 10, 100], [20, 345, 1, 90], [500, 23, 7, 888, 44]
find_first_longest([20, 345, 1, 90])

345

 Escreva uma função chamada find_first_longest que recebe uma lista de números inteiros como argumento e retorna o número com mais dígitos na lista. Se houver dois ou mais números com o mesmo número máximo de dígitos, a função deve retornar o primeiro número encontrado.

Por exemplo:

python
Copy code
assert find_first_longest([1, 10, 100]) == 100
assert find_first_longest([20, 345, 1, 90]) == 345
assert find_first_longest([500, 23, 7, 888, 44]) == 500
Na primeira chamada, a função deve retornar 100 porque é o número com mais dígitos (3 dígitos) na lista [1, 10, 100].

Na segunda chamada, a função deve retornar 345 porque é o número com mais dígitos (3 dígitos) na lista [20, 345, 1, 90].

Na terceira chamada, a função deve retornar 500 porque é o número com mais dígitos (3 dígitos) na lista [500, 23, 7, 888, 44]. Se houver empate, a função deve retornar o primeiro número encontrado, neste caso, 500.

In [7]:
def find_most_frequent_digit(num_int):
    count_zero = 0
    item_com_maior_ocorrencia = None

    for i in num_int:
        tamanho_atual_item = len(str(i))
        if tamanho_atual_item > count_zero:
            count_zero = tamanho_atual_item
            item_com_maior_ocorrencia = i
    return item_com_maior_ocorrencia

find_most_frequent_digit([122333444455555])

122333444455555

Escreva uma função chamada "find_most_frequent_digit" que recebe um número inteiro como argumento e retorna o dígito mais frequente no número. Se houver dois ou mais dígitos com a mesma frequência máxima, a função deve retornar o dígito menor.

Por exemplo, se a entrada for 122333444455555, a função deve retornar 5 porque o dígito 5 aparece mais frequentemente. Se a entrada for 121212, a função deve retornar 1 porque o dígito 1 e o dígito 2 aparecem com a mesma frequência máxima, mas 1 é menor do que 2.